server:
  port: 8080

spring:
  application:
    name: course
  datasource:
    name: epay
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/nycqw
      username: root
      password: root
      filters: [stat,wall,log4j]
  rabbitmq:
    host: 106.14.187.183
    port: 5672
    username: root
    password: 123456
    publisher-confirms: true # 发布确认
    virtual-host: /

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.eden.model

#分页的配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  provider:
    timeout: 1000

